// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzI_1nTz5yoUtFWKGjAo7nU5uH4oB4yms',
    appId: '1:842924955477:web:4e3abb349429c415f441dc',
    messagingSenderId: '842924955477',
    projectId: 'drive-guard-2e4bb',
    authDomain: 'drive-guard-2e4bb.firebaseapp.com',
    storageBucket: 'drive-guard-2e4bb.firebasestorage.app',
    measurementId: 'G-BZMJGFN6QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6eTa0dlq5KLCb9uKqMbrd8m-itwYBf2c',
    appId: '1:842924955477:android:3a00434bf5f28215f441dc',
    messagingSenderId: '842924955477',
    projectId: 'drive-guard-2e4bb',
    storageBucket: 'drive-guard-2e4bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcZU_NeVvgX7BLQZQUXFNnZVSObAmg1eI',
    appId: '1:842924955477:ios:1310fc73080aee59f441dc',
    messagingSenderId: '842924955477',
    projectId: 'drive-guard-2e4bb',
    storageBucket: 'drive-guard-2e4bb.firebasestorage.app',
    iosBundleId: 'com.example.driveguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcZU_NeVvgX7BLQZQUXFNnZVSObAmg1eI',
    appId: '1:842924955477:ios:1310fc73080aee59f441dc',
    messagingSenderId: '842924955477',
    projectId: 'drive-guard-2e4bb',
    storageBucket: 'drive-guard-2e4bb.firebasestorage.app',
    iosBundleId: 'com.example.driveguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzI_1nTz5yoUtFWKGjAo7nU5uH4oB4yms',
    appId: '1:842924955477:web:adbeced4082bd2d4f441dc',
    messagingSenderId: '842924955477',
    projectId: 'drive-guard-2e4bb',
    authDomain: 'drive-guard-2e4bb.firebaseapp.com',
    storageBucket: 'drive-guard-2e4bb.firebasestorage.app',
    measurementId: 'G-5VHNQC5C3F',
  );
}
